<?php

namespace DiscountBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DispoRepository extends \Doctrine\ORM\EntityRepository
{


}
