

services:
#    discount.example:
#        class: DiscountBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.form.type.productType:
        class: DiscountBundle\Form\ProductUpdateType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.Update }
    
    discount.parsexml:
        class: DiscountBundle\Services\ProductDiscountService
        public: true
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]
        
    discount.connectionBdd:
        class: DiscountBundle\Services\ConnectionBddService
        public: true
        